Log Error Prior to Return Error
medik8s/fence-agents-remediation pull request #117
Opened 2024-01-02 12:50 UTC by razo7

Before returning an error to reconcile FAR should log an error. 
It was mostly missed after conditions status update.

2024-01-02 12:56 UTC, razo7 commented
/test 4.14-openshift-e2e
/test 4.15-openshift-e2e

2024-01-02 15:23 UTC, razo7 commented
/test 4.14-openshift-e2e
/test 4.15-openshift-e2e

2024-01-03 06:45 UTC, mshitrit commented
/lgtm

2024-01-03 08:33 UTC, razo7 commented
/retest

2024-01-03 11:28 UTC, razo7 commented
/retest

2024-01-03 11:46 UTC, clobrano requested changes
I wonder if all the error messages after UpdateStatus failures could be put inside UpdateStatus function itself. I also added some other comments in the code.

2024-01-03 11:46 UTC, clobrano commented on controllers/fenceagentsremediation_controller.go
> +	errFailUpdate          = "Failed to update conditons"
typo: s/conditons/conditions

2024-01-03 11:46 UTC, clobrano commented on controllers/fenceagentsremediation_controller.go
> +			notFoundErr = fmt.Errorf("failed to update conditons for reason %s, and error: %v", utils.RemediationFinishedNodeNotFound, err)
Maybe you could wrap the previous error too
Also typo s/conditons/conditions

2024-01-03 13:37 UTC, razo7 commented
>I wonder if all the error messages after UpdateStatus failures could be put inside UpdateStatus function itself.

They can but this way we log an error in the function and Reconcile

2024-01-03 13:46 UTC, clobrano commented
> > I wonder if all the error messages after UpdateStatus failures could be put inside UpdateStatus function itself.
> 
> They can but this way we log an error in the function and Reconcile

Sorry, I meant inside `utils.UpdateConditions`.

IIUC the additional information this new logs provide is the CR's name, which is already accessible inside `utils.UpdateConditions`, so we could simply update the error logs that are inside `utils.UpdateConditions`

2024-01-03 14:19 UTC, razo7 commented
SGTM

2024-01-03 15:03 UTC, clobrano approved these changes

2024-01-03 15:25 UTC, razo7 commented
/retest

2024-01-03 16:29 UTC, merged