Install tools
medik8s/fence-agents-remediation pull request #3
Opened 2023-01-18 08:57 UTC by razo7

2023-01-18 19:40 UTC, slintes requested changes
one nit, otherwise lgtm

2023-01-19 11:24 UTC, clobrano requested changes

2023-01-19 11:24 UTC, clobrano commented on Makefile
> +# operator-framework-tool will delete old package $2, then dowmload $3 to $1.
typo s/dowmload/download

2023-01-19 13:31 UTC, razo7 commented on Makefile
> +define operator-framework-tool
- `install-operator-framework-tool`?
- `operator-framework-install-tool`?

2023-01-19 13:46 UTC, clobrano commented on Makefile
> +define operator-framework-tool
my 2:coin:
Since this uses `curl`, and so it's generic (respect `go-install-tool`), why not just `install-tool` ?

2023-01-19 15:49 UTC, clobrano commented on Makefile
> +define operator-framework-tool
> Good option but I lean to url-install-tool since it install the tool based on it's URL

Which is better indeed :+1:

2023-01-20 10:08 UTC, slintes approved these changes

2023-01-22 07:38 UTC, merged