Update Tool and API Versions
medik8s/fence-agents-remediation pull request #56
Opened 2023-06-12 06:14 UTC by razo7

Bump FAR to the latests tool and API versions (e.g. K8s, OCP, Controller-gent, Kustomize, and Operator-Sdk).

The PR includes some fixes for writing/deleting the envtest target directory, fetching the machine client (for E2E) using OpenShift client-go, and removing kustomize v5 deprecation warnings.

2023-06-12 06:43 UTC, razo7 commented
Golang must be v1.20 prior to merging this PR. 
/hold
Wait for #57 to be merged

2023-06-14 08:19 UTC, razo7 commented
E2E test will fail as it needs https://github.com/openshift/release/pull/40248 to be merged, so Golang version on E2E will be updated

2023-06-14 11:48 UTC, razo7 commented
/retest

2023-06-15 06:35 UTC, mshitrit commented
/lgtm
/hold
Giving others chance to review

2023-06-15 08:55 UTC, clobrano commented
/lgtm

Giving a chance to get more feedbacks, feel free to unhold
/hold

2023-06-25 12:24 UTC, razo7 commented
I hope #20 will be merged soon, and I prefer to wait for this PR to be merged. Since this PR introduce huge bump (by time of versions, not necessarily it's true for functionality of FAR), thus I would prefer to wait for #20.

2023-06-28 11:31 UTC, razo7 commented
E2E PR was merged and this PR is ready for review

2023-06-28 16:14 UTC, slintes requested changes
there changes not relevant to the PR title in the PR
- please revert the kustomize changes and put them in into their own PR. And when doing so, either delete all unneeded and/or commented configs, or migrate all of them to the new format. What we have in this PR now is a mix of everything. I'd prefer to migrate all (and keep them commented), it will make enabling webhooks later on much easier
- there also code changes, probably also worth their own PR?

2023-06-28 16:14 UTC, slintes commented on bundle/manifests/fence-agents-remediation.medik8s.io_fenceagentsremediations.yaml
> +  conditions: null
interesting... in /config this status is removed completely from the CRDs, here just the list values change :thinking: :shrug:

2023-06-28 16:14 UTC, slintes commented on config/crd/kustomization.yaml
> -patchesStrategicMerge:
so... how would we enable webhooks now?

2023-06-28 16:14 UTC, slintes commented on config/default/kustomization.yaml
> -# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER' prefix.
not sure if it's a good idea to remove this certmanager config...

2023-06-29 05:53 UTC, razo7 commented
Ok, I will create PR for changing the OCP client-go and fetching machine client in E2E test and in another PR I will update and fix deprecation warnings due to Kustomize v5 changes.
> migrate all of them to the new format.

When you say new format are you referring to Kubebuilder `go/v3` to `g0/v4`?  I remembered that go/v4 was still as alpha, and looking again I see that it has already been stabilized ECOPROJECT-1315

2023-06-29 07:14 UTC, razo7 commented
> there are also code changes, probably also worth their own PR?

I was thinking of doing another PR for them.

>Ok, I will create PR for changing the OCP client-go and fetching machine client in E2E test

But looking again on the changes, they are quite minor IMHO, and due to bumping the K8s and OCP APIs I was aware of an error with `vet` under vendor due to the old `github.com/openshift/machine-api-operator` package.
Therefore, I would prefer to let the these code changes remain in this PR. 
I can update the PR's title if you still see a need for that.
WDYT?

2023-06-29 09:23 UTC, slintes commented
> > there are also code changes, probably also worth their own PR?
> 
> I was thinking of doing another PR for them.
> 
> > Ok, I will create PR for changing the OCP client-go and fetching machine client in E2E test
> 
> But looking again on the changes, they are quite minor IMHO, and due to bumping the K8s and OCP APIs I was aware of an error with `vet` under vendor due to the old `github.com/openshift/machine-api-operator` package. Therefore, I would prefer to let the these code changes remain in this PR. I can update the PR's title if you still see a need for that. WDYT?

ack, wfm

2023-06-29 09:52 UTC, razo7 commented
Updating to kustomize v5, and removing new deprecation warnings will be done in a follow up PR when we change the project layout to go/v4 - [ECOPROJECT-1315](https://issues.redhat.com//browse/ECOPROJECT-1315)

2023-06-29 10:35 UTC, razo7 commented
/unhold

2023-07-03 11:36 UTC, slintes approved these changes

2023-07-03 11:41 UTC, merged